### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by RayPS** [Brikwerk/joyconpi#1]
Do you think it's possible to achieve the Switch controller automation in hardware side?
I had a cheap fake Switch controller that are well functioning. 
I am thinking if I take the board inside and connect to the Pi by soldering the buttons then simulate the press. I don't know how that rubber part underneath the button interacts with the board.
Do you think it's possible?

It's a pain to cook 20 same dishes repeatedly in Zelda, I really need this.

**Comment by Brikwerk** [comment]
Automation with existing hardware is definitely possible. I've done something similar with a Gameboy before where I used the Pi's GPIO to actuate the buttons. In this instance, if you're willing to take apart an existing controller that works, you could create an automation interface with it. Soldering/hooking things up will really depend upon how it's built, however.

For this project, I think it's a little out of scope to include/investigate anything about this. The aim for now is to create a bluetooth method of connecting that doesn't require any specialized hardware besides the Pi.

I can relate about cooking those dishes though, haha. Gotta get those hearty meals made.
